# Generated by Django 3.1.2 on 2020-11-03 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_app_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addlink',
            name='Kelas',
            field=models.CharField(choices=[('', 'Pilih Kelas...'), ('1', 'Satu'), ('2', 'Dua'), ('3', 'Tiga'), ('4', 'Empat'), ('5', 'Lima'), ('6', 'Enam')], max_length=300),
        ),
    ]
